### ISSUE TITLE
Load latest pre-release ID mapping databases

### ISSUE THREAD

**Issue by pennatula** [BiGCAT-UM/bridgedb-r#14]
Allow users to use the pre-release databases for identifier mapping

**Comment by egonw** [comment]
@pennatula, because Jonathan uses a different filename pattern, you need to give that too, but are you happy with:

    getBridgeNames(
        website="http://bridgedb.org/data/gene_database/pre-release/",
        pattern="Hs_Derby_Ensembl_\\d{2}_v\\d.\\d*.bridge"
    )

?

**Comment by egonw** [comment]
Can also be used to find metabolite databases, though it's really a trick, not a nice API, as it assumes people know about the file name pattern:

    getBridgeNames(pattern="metabolites_\\d*.bridge")
