### ISSUE TITLE
Can I load a local metabolites bridge file ?

### ISSUE THREAD

**Issue by kozo2** [BiGCAT-UM/bridgedb-r#16]
I tried

```R
> mapper <- loadDatabase("./metabolites_20150717.bridge.gz")
Failed to start database 'jar:(./metabolites_20150717.bridge.gz)database', see the next exception for details.
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  org.bridgedb.IDMapperException: Could not connect to database
```

Is it possible to *loadDatabase* a local metabolites bridge file with BridgeDbR ?

**Comment by egonw** [comment]
Kozo, you need to gunzip it first... I have not added support for that yet. BridgeDb itself cannot do this, because it actually uses the file as a live database... So, I would have to gunzip the file in R, and it's likely easier to do it yourself...

**Comment by egonw** [comment]
See also my comment on another issue: https://github.com/BiGCAT-UM/bridgedb-r/issues/14#issuecomment-134854589

**Comment by kozo2** [comment]
I extracted metabolites_20150717.bridge, but still have an error like this.

```
> mapper <- loadDatabase("./metabolites_20150717.bridge")
Database 'jar:(./metabolites_20150717.bridge)database' not found.
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  org.bridgedb.IDMapperException: Could not connect to database
> 
```

**Comment by kozo2** [comment]
Now there is no error for ```loadDatabase``` with
 - java 1.8.0_74
 - metabolites-20160113.bridge
 - bridgedbr 1.4.0

I close this issue, thanks.

**Comment by egonw** [comment]
Thanks for the confirmation! Very much appreciated!
