### ISSUE TITLE
Documentation for browsing metabolite bridge data?

### ISSUE THREAD

**Issue by kozo2** [BiGCAT-UM/bridgedb-r#17]
I tried to browse the mappings in http://bridgedb.org/data/gene_database/metabolites-20160113.bridge.gz
But I couldn't find the way to do this after

```
> loadDatabase("Downloads/metabolites-20160113.bridge")
[1] "Java-Object{Downloads/metabolites-20160113.bridge}"
```

from the current bridgedb-r documentation.

Could you please add the documentation for this?

**Comment by egonw** [comment]
That's weird... there is a man page, with this example:

https://github.com/Bioconductor-mirror/BridgeDbR/blob/master/man/loadDatabase.Rd

What version are you using and where did you get that?

**Comment by kozo2** [comment]
@egonw I'm sorry for my poor English.
I know the man page https://github.com/Bioconductor-mirror/BridgeDbR/blob/master/man/loadDatabase.Rd
and the example

```r
location <- getDatabase("Homo sapiens")
mapper <- loadDatabase(location)
```

What I really want to say is *I could not find the way to use the mapper object for browsing the metabolite ID links* from the current documentation.

**Comment by kozo2** [comment]
@egonw justed wanted to know if there is any update.
I tried to load local metabolite bridge, but `loadDatabase` did not work.
```R
> library(rJava)
> library(BridgeDbR)
> loadDatabase("./metabolites_20160412.bridge")
Failed to start database 'jar:(./metabolites_20160412.bridge)database' with class loader RJavaClassLoader@2666e815, see the next exception for details.
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  org.bridgedb.IDMapperException: Could not connect to database
```

**Comment by egonw** [comment]
@kozo2, OK, (I really need to find some funding to get someone to work on this at least half time; I don't have enough time myself), the issue with loading BridgeDb ID mapping file (the Derby ones) with unknown data sources is now fixed. Confirmed with BridgeDb 2.2.x and the October ID mapping file:

    > library("BridgeDbR")
    Loading required package: rJava
    > loadDatabase("./metabolites_20171008.bridge")
    [1] "Java-Object{./metabolites_20171008.bridge}"

Browsing is not really a feature. Yet. Because I think the Java BridgeDb does have functionality for iterating... but I have no idea when I get to that, given the speed at which things go.

**Comment by kozo2** [comment]
@egonw Thank you for your comment. I checked that the following codes works well on my Windows10 env (Java9, R 3.4.2, BridgeDbR 1.10.2).
```
> library(rJava)
> library(BridgeDbR)
> mapper <- loadDatabase("./metabolites_20170826.bridge")
> map(mapper, "Ce", "15864", "Ck")
[1] "C01514"
```
I will send pull request (about documentation) later.

By the way, can you add KNApSAcK system code to http://www.bridgedb.org/documentation/system-codes/ ?

Thanks.
