### ISSUE TITLE
match function not working properly

### ISSUE THREAD

**Issue by lmbramer** [BiGCAT-UM/bridgedb-r#24]
I installed the package via Bioconductor and am running into the following issue.
I'm trying to use the match function and I currently can't get the package code example to run:

`location <- getDatabase("Mycobacterium tuberculosis")`
`mapper <- loadDatabase(location)` 
`map(mapper, "L", "885041", "X")` 
`map(mapper, "L", "885041")`

And all that is returned is an empty list. I've tried this with several of my own examples where the web service rest API returns items but an empty list is returned using the R package. For example:

`library(BridgeDbR)`
`db = getDatabase("Homo sapiens")`
`mapper = loadDatabase(db)`
`map(mapper = mapper, identifier = "456", source = "Cs", target = "Ck")`
`map(mapper = mapper, identifier = "456", source = "Cs")`

Returns:
`list()`

Here is my session info from R:
`> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] BridgeDbR_1.12.0    rJava_0.9-9         bindrcpp_0.2        pmartRqc_0.9.1      ggplot2_2.2.1       trelliscope_0.9.8  
[7] datadr_0.8.6        dplyr_0.7.4         data.table_1.10.4-3
`

**Comment by egonw** [comment]
The quick answer is that the getDatabase("Homo sapiens") method downloads a gene/protein ID mapping database, and it does not have mappings for metabolites (those are species independent). You can download a metabolite ID mappings databases here

Specifically, the February release is at: https://figshare.com/articles/Metabolite_BridgeDb_ID_Mapping_Database_20180201_/5845134

Save the .bridge file in the same folder as that human ID mapping file and open it with that load() command...

The longer answer is: I need to make this more clear in the documentation!

**Comment by lmbramer** [comment]
Thanks!

**Comment by egonw** [comment]
Section on metabolomics with more detail added: https://github.com/bridgedb/BridgeDbR/commit/ed0a213633b87258c2ce1c65eb66a70ceee14093
