### ISSUE TITLE
unable to load metabolites database

### ISSUE THREAD

**Issue by emiliesecherre** [BiGCAT-UM/bridgedb-r#25]
Hello ! I'm trying to run this code :

```R
utils::download.file("https://ndownloader.figshare.com/files/11438549", "metabolites_20180508.bridge")
locationm = normalizePath("./metabolites_20180508.bridge")
mapperm <- BridgeDbR::loadDatabase(locationm)
```

and i get this error :

```R
> mapperm <- BridgeDbR::loadDatabase(locationm)
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  org.bridgedb.IDMapperException: Could not connect to database
```

how can i fix it please ? I add that i'm using bridgedbR in a devtools package, so the metabolitedb file is downloaded inside the package folder. If i download it somewhere else it works

**Comment by egonw** [comment]
Which version of BridgeDbR are you using? This is not the active repository anymore, but this is: https://github.com/BridgeDb/BridgeDbR

Second, I would also suggest to try to load the most recent metabolite database, which you can find at https://bridgedb.github.io/data/gene_database/

**Comment by emiliesecherre** [comment]
I'm using BridgeDbR 1.22.0, thank you for the recent databases. Unfortunatly, the issue remain the same : if the file is inside the package i'm creating, the database can't be loaded...

**Comment by emiliesecherre** [comment]
Edit : Now its not working at all, no matter where i put the .bridge file... Its always the same issue

**Comment by egonw** [comment]
I'll try to look at it asap. I'm sorry about the trouble :/ (there are a few things overdue I need to finish first...)

**Comment by emiliesecherre** [comment]
no worries, thank you !

**Comment by egonw** [comment]
Okay, first attempt to reproduce it failed. It seems to work with BridgeDb 1.23.1 on Debian GNU/Linux.

**Comment by egonw** [comment]
Okay, works for me with BridgeDb 1.22.0 too. Both were with R 3.6.3. What R version are you using?

**Comment by egonw** [comment]
Okay, installed R 4.0 and BridgeDbR 1.22, still works :( Okay, I'm starting to get convinced we're looking at a OS-level issue. @emiliesecherre, can you plz tell me your operating system, R version (for completeness, but I guess 4.0), and the value of `locationm`?

**Comment by emiliesecherre** [comment]
I have R 4.0.2, BridgeDbR 1.22.0, Windows 10 (last version) and locationm is "C:\\Users\\Thanael\\Documents\\promethee\\metabo.bridge" (i renamed the metabolite db). The weird thing is that i works only with some folders, like "Downloads" one, but not for others..

**Comment by egonw** [comment]
Okay, thanks. I was able to reproduce the problem with Java8, Win10, RStudio, and R 3.6.3.

I'll have to do some debugging to figure out what goes wrong. I don't get much info here either :/

**Comment by emiliesecherre** [comment]
Okay it's just about a package i'm building, i can't use the metabolite db if its inside the package folder.

**Comment by egonw** [comment]
I have been thinking about this anyway... there are plenty of Bioconductor data packages, but I do not have time to explore how to create those.

PS. I'm doing some updates to the BridgeDb Java code to get some better feedback to get an idea what goes wrong, but did not finish that yet.

**Comment by DeniseSl22** [comment]
Moved to https://github.com/bridgedb/BridgeDbR/issues/28
