### ISSUE TITLE
Things to do for next release

### ISSUE THREAD

**Issue by pennatula** [BiGCAT-UM/bridgedb-r#5]
Checking exported objects have runnable examples...
    * CONSIDER: Adding runnable examples to the following man pages
      which document exported objects:
      getDatabase.Rd, loadDatabase.Rd, map.Rd
Checking formatting of DESCRIPTION, NAMESPACE, man pages, R source,
  and vignette source...
    * CONSIDER: Shortening lines; 35 lines (6%) are > 80 characters
      long.
    * CONSIDER: Replacing tabs with 4 spaces; 6 lines (1%) contain
      tabs.
    * CONSIDER: Indenting lines with a multiple of 4 spaces; 104 lines
      (19%) are not.
  See http://bioconductor.org/developers/how-to/coding-style/

**Comment by egonw** [comment]
"Adding runnable examples to the following man pages"...

Not sure :) Running those examples are rather expensive...

**Comment by egonw** [comment]
Others filed separately as issues #9, #10, and #11.
