### ISSUE TITLE
Database can't be opened

### ISSUE THREAD

**Issue by vdtoorn** [BiGCAT-UM/bridgedb-r#8]
Dear BridgeDbR development team,

I like this package and wanted to present it at a course for advanced R. Unfortunately, when I tried it on Windows (the course computers use it), I found there is an issue with the bridge file downloaded by R. I think the file is downloaded the wrong way (e.g. text mode) and therefore Derby isn't able to open it. When I download the file manually, loadDatabase works correctly.

Unfortunately, I can't use the it in the course because of this, but I thought I'd take the time to tell you about it.

The version of R I use is 3.1.2 (64 bit) on windows 8.1, and Java version 1.8.0_25 (64 bit). BridgeDbR version is version 1.0.0 according to the packages list in RStudio.

**Comment by egonw** [comment]
@vdtoorn thanks for the catch. I had missed this bug report, unfortunately.

I have applied a patch (https://github.com/BiGCAT-UM/bridgedb-r/commit/c719e9d637adac732b74fb931873d99fc1a96212), applying your suggestion.

I would appreciate if you could let me know if it fixes your problem. I tried it on Win7 and it worked there... (which says nothing...)

**Comment by vdtoorn** [comment]
Hi Egon, I've not used the library for a while, but I'll have a look if it's fixed. Thanks for your response!
